a solid bounded by a cylindrical surface and two parallel planes (the bases)
a surface generated by rotating a parallel line around a fixed line
a chamber within which piston moves
a cylindrical container for oxygen or compressed air
